version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Testing...
      - npm run test
      - echo stop Testing
      - npm stop
      - echo Building...
      - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: yes
  base-directory: dist
