version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Testing...
      - npm run build

artifacts:
  files:
    - buildspec.yml
    - build/*
  discard-paths: no
  base-directory: dist
